-- Keybinding localization
BINDING_HEADER_TARGET_TOOL = "Target Tool"
BINDING_NAME_OGTT_LASTTARGET = "Target Last Target"
BINDING_NAME_OGTT_LASTPOOLTARGET = "Target Last Pool Target"
BINDING_NAME_OGTT_NEXTPOOLTARGET = "Target Next Pool Target"
BINDING_NAME_OGTT_INCREASEPOOLSIZE = "Increase Pool Size"
BINDING_NAME_OGTT_DECREASEPOOLSIZE = "Decrease Pool Size"
